<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('feedback')->__('Feedback') ?></h1>
</div>

<form action="<?php echo $this->getUrl('feedback/index/save'); ?>"  id="feedback" method="post">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('feedback')->__('Feedback Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('feedback')->__('Name') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('feedback')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('feedback')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('feedback')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
            </li>
            
           
            <li class="wide">
                <label for="comments" class="required"><em>*</em><?php echo Mage::helper('feedback')->__('Comments') ?></label>
                <div class="input-box">
                    <textarea name="comments" id="comments" title="<?php echo Mage::helper('feedback')->__('Comments') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('feedback')->__('* Required Fields') ?></p>
        <button type="submit" title="<?php echo Mage::helper('feedback')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('feedback')->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('feedback', true);
//]]>
</script>
